spring:
  datasource:
    druid:
      h2:
        url: jdbc:h2:mem:test_db
        username: sa
        password: unaboot123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:  org.h2.Driver
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver